### ISSUE TITLE
Try to use connect api for the monstercat browser instead of imgur and soundcloud api

### ISSUE THREAD

**Issue by GiovanniMCMXCIX** [gamehelp16/monstercat-browser-old#13]
Monstercat Connect has and API that can help you with the website that will be more easier to get the tracks for streaming on the website, the album art, durations amd more

Here is a doc for more info:
https://www.monstercat.com/dev/api/connect

Note:
It doest require an account to use the api, except the playlists

**Comment by gamehelp16** [comment]
To the readers (if you somehow stumble upon this issue): this has been discussed via Reddit PM.
